global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'model'
    static_configs:
      - targets: ['torchserve:8082']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'web'
    static_configs:
      - targets: ['web:8000']
