name: Publish Docker images to GHCR

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build Docker Images
        run: |
          docker-compose -f Docker/docker-compose.yml build torchserve web_backend web_frontend data_processing

      - name: List Docker Images
        run: docker images

      - name: Capture and Tag Docker Images
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          # Capture the actual image names
          DOCKER_TORCHSERVE=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E "${REPO_NAME}.*torchserve" | head -n 1)
          DOCKER_WEB_BACKEND=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E "${REPO_NAME}.*web_backend" | head -n 1)
          DOCKER_WEB_FRONTEND=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E "${REPO_NAME}.*web_frontend" | head -n 1)
          DOCKER_DATA_PROCESSING=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E "${REPO_NAME}.*data_processing" | head -n 1)

          echo "TorchServe image: $DOCKER_TORCHSERVE"
          echo "Web Backend image: $DOCKER_WEB_BACKEND"
          echo "Web Frontend image: $DOCKER_WEB_FRONTEND"
          echo "Data Processing image: $DOCKER_DATA_PROCESSING"

          # Tag the images correctly
          docker tag $DOCKER_TORCHSERVE ghcr.io/${REPO_NAME}/torchserve:latest
          docker tag $DOCKER_WEB_BACKEND ghcr.io/${REPO_NAME}/web_backend:latest
          docker tag $DOCKER_WEB_FRONTEND ghcr.io/${REPO_NAME}/web_frontend:latest
          docker tag $DOCKER_DATA_PROCESSING ghcr.io/${REPO_NAME}/data_processing:latest

      - name: Push Docker Images
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${REPO_NAME}/torchserve:latest
          docker push ghcr.io/${REPO_NAME}/web_backend:latest
          docker push ghcr.io/${REPO_NAME}/web_frontend:latest
          docker push ghcr.io/${REPO_NAME}/data_processing:latest

        env:
          DOCKER_BUILDKIT: 1