name: Publish Docker images to GHCR

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build Docker Images
        run: |
          docker-compose -f Docker/docker-compose.yml build torchserve web_backend web_frontend data_processing

      - name: List Docker Images
        run: docker images

      - name: Tag and Push Docker Images
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          # Check for the correct image name by listing images
          DOCKER_TORCHSERVE=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "${REPO_NAME}_torchserve")
          DOCKER_WEB_BACKEND=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "${REPO_NAME}_web_backend")
          DOCKER_WEB_FRONTEND=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "${REPO_NAME}_web_frontend")
          DOCKER_DATA_PROCESSING=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "${REPO_NAME}_data_processing")

          # Tag the images correctly
          docker tag $DOCKER_TORCHSERVE ghcr.io/${REPO_NAME}/torchserve:latest
          docker tag $DOCKER_WEB_BACKEND ghcr.io/${REPO_NAME}/web_backend:latest
          docker tag $DOCKER_WEB_FRONTEND ghcr.io/${REPO_NAME}/web_frontend:latest
          docker tag $DOCKER_DATA_PROCESSING ghcr.io/${REPO_NAME}/data_processing:latest

          # Push the images
          docker push ghcr.io/${REPO_NAME}/torchserve:latest
          docker push ghcr.io/${REPO_NAME}/web_backend:latest
          docker push ghcr.io/${REPO_NAME}/web_frontend:latest
          docker push ghcr.io/${REPO_NAME}/data_processing:latest

        env:
          DOCKER_BUILDKIT: 1
