name: Publish Docker images to GHCR

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and Tag Docker Images
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker-compose -f Docker/docker-compose.yml build torchserve web_backend web_frontend data_processing
          docker tag Docker_torchserve ghcr.io/${REPO_NAME}/torchserve:latest
          docker tag Docker_web_backend ghcr.io/${REPO_NAME}/web_backend:latest
          docker tag Docker_web_frontend ghcr.io/${REPO_NAME}/web_frontend:latest
          docker tag Docker_data_processing ghcr.io/${REPO_NAME}/data_processing:latest

      - name: Push Docker Images
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker-compose -f Docker/docker-compose.yml push torchserve web_backend web_frontend data_processing
          docker push ghcr.io/${REPO_NAME}/torchserve:latest
          docker push ghcr.io/${REPO_NAME}/web_backend:latest
          docker push ghcr.io/${REPO_NAME}/web_frontend:latest
          docker push ghcr.io/${REPO_NAME}/data_processing:latest

        env:
          DOCKER_BUILDKIT: 1
